# Generated by Django 5.2.15 on 2026-06-17 01:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trader",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=30, unique=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("moore", "Mooré"),
                            ("dioula", "Dioula"),
                            ("fulfulde", "Fulfuldé"),
                            ("fr", "Français"),
                        ],
                        default="moore",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "traders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrustScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("transaction_count", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=0, default=0, max_digits=14),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "trader",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_score",
                        to="core.trader",
                    ),
                ),
            ],
            options={
                "db_table": "trust_scores",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "type",
                    models.CharField(
                        choices=[("VENTE", "Vente"), ("ACHAT", "Achat")], max_length=10
                    ),
                ),
                ("raw_transcript", models.TextField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("REAL", "Pipeline IA réel"),
                            ("OZ", "Mode Oz (simulation)"),
                            ("WHATSAPP", "WhatsApp"),
                            ("WEB", "Interface web"),
                        ],
                        default="WEB",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.trader",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["trader", "created_at"],
                        name="transaction_trader__4ccafc_idx",
                    ),
                    models.Index(
                        fields=["trader", "type"], name="transaction_trader__2f3f25_idx"
                    ),
                ],
            },
        ),
    ]
