# Generated by Django 6.0.7 on 2026-07-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trader',
            name='password',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='trader',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('premium', 'Premium')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('REAL', 'Pipeline IA réel'), ('OZ', 'Mode Oz'), ('WHATSAPP', 'WhatsApp'), ('WEB', 'Interface web')], default='WEB', max_length=20),
        ),
    ]