# Generated by Django 5.2.15 on 2026-07-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_trader_is_premium_trader_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trader",
            name="password",
            field=models.CharField(default="", max_length=256),
        ),
    ]
